/* =============================================================
   Popular plans shown in the scrolling band at the end of each
   product page (1-2 well-known plans from each leading insurer).

   Compiled Oct 2026 from general market knowledge, NOT from
   insurer feeds: insurers rename and withdraw plans regularly,
   so VERIFY these names before go-live and review them every
   quarter. `id` must match an insurer id in
   pages/servicesupport/servicesupport.data.ts (used for the logo);
   use `name` for insurers not in that list.
   ============================================================= */

export interface PopularPlan {
  plan: string;
  id?: string;
  name?: string;
}

export type MarqueeCategory =
  | 'health' | 'term' | 'guaranteed' | 'ulip' | 'ci' | 'pa'
  | 'general' | 'fire' | 'motor' | 'corporate' | 'group' | 'pet';

export const POPULAR_PLANS: Record<MarqueeCategory, PopularPlan[]> = {
  health: [
    { id: 'star', plan: 'Star Comprehensive' },
    { id: 'star', plan: 'Family Health Optima' },
    { id: 'care', plan: 'Care Supreme' },
    { id: 'care', plan: 'Care Advantage' },
    { id: 'niva-bupa', plan: 'ReAssure 2.0' },
    { id: 'niva-bupa', plan: 'Aspire' },
    { id: 'hdfc-ergo', plan: 'Optima Secure' },
    { id: 'hdfc-ergo', plan: 'Optima Restore' },
    { id: 'icici-lombard', plan: 'Elevate' },
    { id: 'icici-lombard', plan: 'Health AdvantEdge' },
    { id: 'abhi', plan: 'Activ One' },
    { id: 'tata-aig', plan: 'Medicare Premier' },
    { id: 'bajaj-general', plan: 'Health Guard' },
    { id: 'manipalcigna', plan: 'Sarvah' },
    { id: 'manipalcigna', plan: 'ProHealth Prime' },
    { id: 'new-india', plan: 'Family Floater Mediclaim' },
    { id: 'sbi-general', plan: 'Super Health' },
  ],
  term: [
    { id: 'lic', plan: 'Digi Term' },
    { id: 'lic', plan: 'Jeevan Amar' },
    { id: 'hdfc-life', plan: 'Click 2 Protect Supreme' },
    { id: 'hdfc-life', plan: 'Click 2 Protect Super' },
    { id: 'icici-pru', plan: 'iProtect Smart' },
    { id: 'axis-max', plan: 'Smart Secure Plus' },
    { id: 'axis-max', plan: 'Smart Term Plan Plus' },
    { id: 'sbi-life', plan: 'eShield Next' },
    { id: 'tata-aia', plan: 'Sampoorna Raksha Promise' },
    { id: 'bajaj-life', plan: 'eTouch II' },
    { id: 'kotak-life', plan: 'e-Term' },
    { id: 'absli', plan: 'DigiShield Plan' },
    { name: 'PNB MetLife', plan: 'Mera Term Plan Plus' },
    { id: 'bandhan-life', plan: 'iTerm Prime' },
    { id: 'canara-hsbc', plan: 'iSelect Smart360' },
  ],
  guaranteed: [
    { id: 'hdfc-life', plan: 'Sanchay Plus' },
    { id: 'hdfc-life', plan: 'Sanchay Par Advantage' },
    { id: 'icici-pru', plan: 'GIFT Pro' },
    { id: 'axis-max', plan: 'Smart Wealth Advantage Guarantee' },
    { id: 'tata-aia', plan: 'Fortune Guarantee Plus' },
    { id: 'bajaj-life', plan: 'Guaranteed Wealth Goal' },
    { id: 'bajaj-life', plan: 'Assured Wealth Goal' },
    { id: 'sbi-life', plan: 'Smart Platina Assure' },
    { id: 'kotak-life', plan: 'Guaranteed Fortune Builder' },
    { id: 'absli', plan: 'Nishchit Aayush' },
    { name: 'PNB MetLife', plan: 'Guaranteed Future Plan' },
    { id: 'lic', plan: 'Jeevan Utsav' },
    { id: 'lic', plan: 'Bima Jyoti' },
  ],
  ulip: [
    { id: 'hdfc-life', plan: 'Click 2 Invest' },
    { id: 'hdfc-life', plan: 'Sampoorna Nivesh Plus' },
    { id: 'icici-pru', plan: 'Signature Assure' },
    { id: 'axis-max', plan: 'Online Savings Plan' },
    { id: 'axis-max', plan: 'Flexi Wealth Advantage' },
    { id: 'sbi-life', plan: 'eWealth Plus' },
    { id: 'sbi-life', plan: 'Smart Fortune Builder' },
    { id: 'tata-aia', plan: 'Param Raksha Life Pro' },
    { id: 'bajaj-life', plan: 'Goal Assure IV' },
    { id: 'kotak-life', plan: 'e-Invest' },
    { id: 'absli', plan: 'Fortune Elite' },
    { name: 'PNB MetLife', plan: 'Goal Ensuring Multiplier' },
    { id: 'lic', plan: 'SIIP' },
    { id: 'lic', plan: 'Index Plus' },
  ],
  ci: [
    { id: 'hdfc-ergo', plan: 'Critical Illness Insurance' },
    { id: 'star', plan: 'Star Critical Illness Multipay' },
    { id: 'care', plan: 'Care Heart' },
    { id: 'niva-bupa', plan: 'CritiCare' },
    { id: 'abhi', plan: 'Activ Secure: Critical Illness' },
    { id: 'bajaj-general', plan: 'Critical Illness Policy' },
    { id: 'tata-aig', plan: 'Criti-Medicare' },
    { id: 'manipalcigna', plan: 'Lifestyle Protection: Critical Care' },
    { id: 'icici-lombard', plan: 'Critical Illness Insurance' },
    { id: 'hdfc-life', plan: 'Cardiac Care' },
    { id: 'hdfc-life', plan: 'Cancer Care' },
    { id: 'icici-pru', plan: 'Heart / Cancer Protect' },
  ],
  pa: [
    { id: 'icici-lombard', plan: 'Personal Protect' },
    { id: 'hdfc-ergo', plan: 'Personal Accident Policy' },
    { id: 'bajaj-general', plan: 'Premium Personal Guard' },
    { id: 'tata-aig', plan: 'Accident Guard Plus' },
    { id: 'star', plan: 'Accident Care Individual' },
    { id: 'care', plan: 'Care Secure' },
    { id: 'abhi', plan: 'Activ Secure: Personal Accident' },
    { id: 'new-india', plan: 'Individual Personal Accident' },
    { id: 'sbi-general', plan: 'Individual Personal Accident' },
    { id: 'digit', plan: 'Personal Accident Insurance' },
    { id: 'indusind-general', plan: 'Personal Accident Insurance' },
  ],
  general: [
    { id: 'tata-aig', plan: 'Travel Guard Plus' },
    { id: 'icici-lombard', plan: 'International Travel Insurance' },
    { id: 'hdfc-ergo', plan: 'Explorer Travel Insurance' },
    { id: 'bajaj-general', plan: 'Travel Prime' },
    { id: 'care', plan: 'Care Explore' },
    { id: 'digit', plan: 'International Travel Insurance' },
    { id: 'hdfc-ergo', plan: 'Home Shield' },
    { id: 'icici-lombard', plan: 'Complete Home Protect' },
    { id: 'bajaj-general', plan: 'My Home All Risk' },
    { id: 'tata-aig', plan: 'Home Secure' },
    { id: 'sbi-general', plan: 'Bharat Griha Raksha' },
    { id: 'new-india', plan: 'Bharat Griha Raksha' },
    { id: 'digit', plan: 'Home Insurance' },
  ],
  fire: [
    { id: 'new-india', plan: 'Bharat Laghu Udyam Suraksha' },
    { id: 'icici-lombard', plan: 'Standard Fire & Special Perils' },
    { id: 'hdfc-ergo', plan: 'Bharat Sookshma Udyam Suraksha' },
    { id: 'tata-aig', plan: 'Standard Fire & Special Perils' },
    { id: 'bajaj-general', plan: 'Bharat Laghu Udyam Suraksha' },
    { id: 'united-india', plan: 'Bharat Sookshma Udyam Suraksha' },
    { id: 'oriental', plan: 'Standard Fire & Special Perils' },
    { id: 'national', plan: 'Bharat Griha Raksha' },
    { id: 'sbi-general', plan: 'Bharat Laghu Udyam Suraksha' },
    { id: 'iffco-tokio', plan: 'Standard Fire & Special Perils' },
  ],
  motor: [
    { id: 'icici-lombard', plan: 'Private Car Package Policy' },
    { id: 'hdfc-ergo', plan: 'Comprehensive Car Insurance' },
    { id: 'hdfc-ergo', plan: 'Two Wheeler Insurance' },
    { id: 'bajaj-general', plan: 'Drive Smart' },
    { id: 'tata-aig', plan: 'Auto Secure: Private Car' },
    { id: 'tata-aig', plan: 'Commercial Vehicle Package' },
    { id: 'digit', plan: 'Car Insurance' },
    { name: 'Acko', plan: 'Comprehensive Car Insurance' },
    { id: 'sbi-general', plan: 'Private Car Insurance' },
    { id: 'new-india', plan: 'Private Car Policy' },
    { id: 'royal-sundaram', plan: 'Private Car Insurance' },
    { id: 'shriram', plan: 'Commercial Vehicle Insurance' },
  ],
  corporate: [
    { id: 'icici-lombard', plan: 'Directors & Officers Liability' },
    { id: 'tata-aig', plan: 'Cyber Insurance' },
    { id: 'hdfc-ergo', plan: 'Commercial General Liability' },
    { id: 'bajaj-general', plan: 'Professional Indemnity' },
    { id: 'new-india', plan: 'Marine Cargo Insurance' },
    { id: 'sbi-general', plan: 'Business Interruption' },
    { id: 'united-india', plan: 'Contractors All Risk' },
    { id: 'iffco-tokio', plan: 'Shopkeepers Insurance' },
    { id: 'chola-ms', plan: 'Office Package Policy' },
    { id: 'royal-sundaram', plan: 'Burglary Insurance' },
  ],
  group: [
    { id: 'icici-lombard', plan: 'Group Health Insurance' },
    { id: 'star', plan: 'Star Group Health Insurance' },
    { id: 'care', plan: 'Group Care 360°' },
    { id: 'hdfc-ergo', plan: 'Group Health Insurance' },
    { id: 'niva-bupa', plan: 'Group Health Insurance' },
    { id: 'hdfc-life', plan: 'Group Term Life' },
    { id: 'icici-pru', plan: 'Group Term Life' },
    { id: 'sbi-life', plan: 'Sampoorn Suraksha' },
    { id: 'lic', plan: 'New Group Term Assurance' },
    { id: 'tata-aig', plan: 'Group Personal Accident' },
    { id: 'bajaj-general', plan: "Employee's Compensation" },
  ],
  pet: [
    { id: 'bajaj-general', plan: 'Pet Dog Insurance' },
    { id: 'tata-aig', plan: 'Pet Insurance' },
    { id: 'hdfc-ergo', plan: 'Paws & Claws' },
    { id: 'generali-central', plan: 'Pet Dog Insurance' },
    { id: 'new-india', plan: 'Canine Insurance' },
    { id: 'oriental', plan: 'Pet Dog Insurance' },
    { id: 'united-india', plan: 'Pet Dog Insurance' },
  ],
};
